application_name:
  default: "mCMS"
email_from:
  default: "from@example.com"
conference_url:
  default: "https://www.appear.in/$room_number$"
open_new_tab_url:
  default: 'true'
use_iframe:
  default: 'true'
whitelist_ip:
  default: '*.*.*.*'
blacklist_ip:
  default: ''
user_default_state:
  default: 'false'
remember_for:
  default: 2
expire_after:
  default: 180
timeout_in:
  default: 15
maximum_attempts:
  default: 5
unlock_in:
  default: 60
format_date:
  default: "%d/%m/%Y"
google_map_key:
  default: "AIzaSyBgNAFiZb48uAk4jb4U0gRSeuHQS9EuCyk"
email_header:
  default: ""
news_limit:
  default: 5
spreadsheet_limit:
  default: 50
email_footer:
  default: |-
    You have received this notification because you have either subscribed to it, or are involved in it.
